[theme]
primaryColor = "#333333"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#262730"

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false 